// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pknfqleszevokgoyvlag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrbmZxbGVzemV2b2tnb3l2bGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTg3NDksImV4cCI6MjA2MzI5NDc0OX0.GWqORYdSlduEuQUMrvzTrJXI4ynOc8yqt_4KHd_aQ3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);